name: 🐛 Bug report
description: Report broken functionality.
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        - Avoid generic or vague titles such as "Something's not working" or "A couple of problems" — be as descriptive as possible.
        - Keep your issue focused on one single problem. If you have multiple bug reports, please create a separate issue for each of them.
        - Issues should represent **complete and actionable** work items. If you are unsure about something or have a question, please start a [discussion](https://github.com/fsharp/FsAutoComplete/discussions/new/choose) instead.
        - Remember that **FsAutocomplete** is an open-source project funded by the community contributions and free time.
        ___

  - type: input
    attributes:
      label: Version
      description: |
        Which version of the package does this bug affect? Make sure you're not using an outdated version.
        - If you are using VSCode, the version of Ionide can be used. You can can find this by going to `View -> Extensions -> Ionide for F#`. It will be displayed next to the name at the top.
        - If you are using the tool directly, you can find the version by running `dotnet fsautocomplete --version` in your terminal.
      placeholder: v1.0.0
    validations:
      required: true

  - type: textarea
    attributes:
      label: Dotnet Info
      description: What is the output of `dotnet --info`?
      placeholder: "Paste output here"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: >
        Minimum steps required to reproduce the bug, including prerequisites, code snippets, or other relevant items.
        The information provided in this field must be readily actionable, meaning that anyone should be able to reproduce the bug by following these steps.
        If the reproduction steps are too complex to fit in this field, please provide a link to a repository instead.
        ⚠️ If you don't provide actionable reproduction steps, your issue won't be investigated. ⚠️
      placeholder: |
        - Step 1
        - Step 2
        - Step 3
    validations:
      required: true

  - type: textarea
    attributes:
      label: Details
      description: Clear and thorough explanation of the bug, including any additional information you may find relevant.
      placeholder: |
        - Expected behavior: ...
        - Actual behavior: ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs
      description: >
        Please add any logs from your LSP client or server that you think might be relevant.
        Be sure to look through logs and obfuscate anything you don't want to share.

        * For VSCode:
          * Enable `FSharp.verboseLogging` and set `FSharp.trace.server` to a higher level
          * Then copy output from
            * `View -> Output -> Fsharp`
            * `View -> Output -> Ionide`
            * Any others that you think might be relevant
      placeholder: |
        - [21:11:05 DEBUG] [LanguageService] FSAC (NETCORE): ...
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Checklist
      description: Quick list of checks to ensure that everything is in order.
      options:
        - label: I have looked through existing issues to make sure that this bug has not been reported before
          required: true
        - label: I have provided a descriptive title for this issue
          required: true
        - label: I have made sure that that this bug is reproducible on the latest version of the package
          required: true
        - label: I have provided all the information needed to reproduce this bug as efficiently as possible
          required: true
        - label: I or my company would be willing to contribute this fix
          required: false

  - type: markdown
    attributes:
      value: |
        If you are struggling to provide actionable reproduction steps, or if something else is preventing you from creating a complete bug report, please start a [discussion](https://github.com/fsharp/FsAutoComplete/discussions/new/choose) instead.
